name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "22 0 * * *"

jobs:
  publish-artifacts:
    name: Publish artifacts to Apache Nexus
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/incubator-pekko-persistence-cassandra'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Publish to Apache Maven repo
        run: sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

      - name: Build Documentation
        run: |-
          sbt docs/paradox unidoc

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create nightly directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-persistence-cassandra/${{ github.ref_name }}-snapshot/
          mv docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-cassandra/${{ github.ref_name }}-snapshot/docs
          mv target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-cassandra/${{ github.ref_name }}-snapshot/api

      - name: Upload nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-cassandra/${{ github.ref_name }} # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
