name: Publish 1.0 jars nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "23 0 * * *"

jobs:
  publish-artifacts:
    name: Publish artifacts to Apache Nexus
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/pekko-persistence-cassandra'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: 1.0.x

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Publish to Apache Maven repo
        run: sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
